# Generated by Django 2.2.6 on 2019-10-30 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bd',
            new_name='Bb',
        ),
    ]
