"""
Django settings for maxwell project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-b_&07!uf_^nw3w526u=k0-)*esndo_9$&)^-!y8g-t5j)r62v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'labor.apps.LaborConfig', # этот класс LaborConfig определен в apps.py
    # 'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'index'    # адрес, по которму перенаправляется пользователь после авторизации
LOGOUT_REDIRECT_URL = 'login'

ROOT_URLCONF = 'maxwell.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [

    # по умолчанию django ищет файлы шаблонов в папке приложения templates
    # мы же подключим папку templates для всего приложения, которая будет уже
    # располагаться уровнем выше, т.е. в папке maxwell:    
            os.path.join(BASE_DIR, 'templates')
            # BASE_DIR содержит полный путь до папки с проектом
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'maxwell.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# устанавливается база данных MySQL, и создаваемый при этом пароль вбивается
# в PASSWORD. Создается база данных, и его имя вбивается в NAME.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'main_db',
        'USER': 'root',
        'PASSWORD': 'Schrodinger%23126787',
        # 'HOST': 'localhost'
    }
}
# Далее суперпользователя сайта можно создать коммандой
# python manage.py createsuperuser

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# по умолчанию django ищет статические файлы в папке приложения strtic
# мы же подключим папку static для всего проекта, которая будет уже
# располагаться уровнем выше, т.е. в папке maxwell:

STATICFILES_DIRS = [
    # подключаем папку со статическими файлами:
    os.path.join(BASE_DIR, 'static')
    # BASE_DIR содержит полный путь до папки с проектом
]
