# Generated by Django 2.2.7 on 2019-11-16 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskType', models.CharField(db_index=True, default='', max_length=50, verbose_name='Task Type')),
            ],
            options={
                'verbose_name': 'Task Type',
                'verbose_name_plural': 'Task Types',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=150)),
                ('discribe', models.TextField(blank=True, null=True, verbose_name='Discribtion')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Days')),
                ('hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hours')),
                ('minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Minutes')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='labor.Tag', verbose_name='Tag')),
                ('taskType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='labor.TaskType', verbose_name='Task Type')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
